branches:
  only:
    - master

language: c

os: linux
dist: bionic
sudo: required

services:
  - docker


env:
  jobs:
    #- NIM_VERSION='1.2.2'
    - NIM_VERSION='latest'
  global:
    - DOCKER_IMG="nimlang/nim:$NIM_VERSION-alpine"


_shared_job: &shared_job
  before_install:
    - docker pull "$DOCKER_IMG"
  script:
    - docker run -v "$(pwd):/project" -w /project -e NIM_BACKEND="$NIM_BACKEND" "$DOCKER_IMG" sh -c "nimble install -dy && nimble test"


jobs:
  include:
    - env: NIM_BACKEND='cc'
      <<: *shared_job

    - env: NIM_BACKEND='cpp'
      <<: *shared_job

    - env: NIM_BACKEND='js'
      <<: *shared_job

  allow_failures:
    - env: NIM_BACKEND='js'
