branches:
  only:
    - master

language: c

os: linux
dist: bionic

services:
  - docker


env:
  global:
    - DOCKER_IMG='nimlang/nim:latest-alpine'


_shared_job: &shared_job
  install: skip
  before_script:
    - docker pull "$DOCKER_IMG"
  script:
    - docker run "$DOCKER_IMG" nim --version
    - docker run -v "$(pwd):/project" -w /project -e NIM_BACKEND="$NIM_BACKEND" "$DOCKER_IMG" sh -c "nimble install -dy && nimble test"


jobs:
  include:
    - name: Test suite (C)
      env: NIM_BACKEND='cc'
      <<: *shared_job

    - name: Test suite (C++)
      env: NIM_BACKEND='cpp'
      <<: *shared_job

    - name: Test suite (Node.js)
      env: NIM_BACKEND='js'
      <<: *shared_job

  allow_failures:
    - env: NIM_BACKEND='js'
