name: CI Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        backend: [cc, cpp]
        experimental: [false]
        include:
          - backend: js
            experimental: true

    name: 'Backend ${{ matrix.backend }}'
    runs-on: ubuntu-latest
    container:
      image: 'nimlang/nim:latest-alpine'
      env:
        NIM_BACKEND: '${{ matrix.backend }}'
    timeout-minutes: 15
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Nim version'
        run: nim --version
      - name: 'Build and run the tests'
        run: |
          nimble install -dy
          nimble test
