name: GitHub Pages
on:
  push:
    branches:
      #- master
      - cd_build_api_docs_gh-pages
    #paths:
      #- 'nim_iterator_stream_experiment/**.nim'


jobs:
  build:
    name: 'API doc'
    runs-on: ubuntu-latest
    container: 'nimlang/nim:latest-alpine'
    timeout-minutes: 15

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Build API doc'
        run: nimble docs

      - name: 'Upload artifact'
        uses: 'actions/upload-artifact@v2'
        with:
          name: 'doc'
          path: '.nimcache/docs/*'
